name: ci-on-sched

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  # This workflow contains a single job called "build"
  build-joplin-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: pre-reqs
        run: sudo ./pre-reqs.sh

      - name: build southof-joplin-server
        run: ./build-joplin-server.sh

      - name: push tag
        uses: anothrNick/github-tag-action@1.67.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          CUSTOM_TAG: 

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
